USE [master]
GO
/****** Object:  Database [PRN221_Project_QLNS]    Script Date: 18/03/2023 6:49:38 CH ******/
CREATE DATABASE [PRN221_Project_QLNS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRN221_Project_QLNS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PRN221_Project_QLNS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PRN221_Project_QLNS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PRN221_Project_QLNS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PRN221_Project_QLNS] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PRN221_Project_QLNS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ARITHABORT OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET  MULTI_USER 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PRN221_Project_QLNS] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PRN221_Project_QLNS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PRN221_Project_QLNS] SET QUERY_STORE = OFF
GO
USE [PRN221_Project_QLNS]
GO
/****** Object:  Table [dbo].[account]    Script Date: 18/03/2023 6:49:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[account](
	[account_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](20) NOT NULL,
	[password] [varchar](20) NOT NULL,
	[isadmin] [bit] NOT NULL,
	[ismanager] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[account_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
/****** Object:  Table [dbo].[profile]    Script Date: 18/03/2023 6:49:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[profile](
	[profile_id] [int] IDENTITY(1,1) NOT NULL,
	[account_id] int NOT NULL,
	[first_name] [varchar](20) NOT NULL,
	[last_name] [varchar](20) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[phone_number] [varchar](20) NULL,
	[hire_date] [varchar](20) NOT NULL,
	[job] [varchar](40) NOT NULL,
	[report_to] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[profile_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[task]    Script Date: 18/03/2023 6:49:38 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[task](
	[task_id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](35) NOT NULL,
	[description] [varchar](MAX) NOT NULL,
	[deadline] [date] NULL,
	[status] [int] NULL,
	[assigned] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[task_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[profile]  WITH CHECK ADD FOREIGN KEY([account_id])
REFERENCES [dbo].[account] ([account_id])
GO
ALTER TABLE [dbo].[profile]  WITH CHECK ADD FOREIGN KEY([report_to])
REFERENCES [dbo].[profile] ([profile_id])
GO
ALTER TABLE [dbo].[task]  WITH CHECK ADD FOREIGN KEY([assigned])
REFERENCES [dbo].[profile] ([profile_id])
GO
USE [master]
GO
ALTER DATABASE [PRN221_Project_QLNS] SET  READ_WRITE 
GO
